### PR TITLE
Fix select menu

### LINKED ISSUE #747: Can't select task to account
I have created task
created task
I want to assignee this task to account
cant select task to account
Console error
consloe error

Steps to reproduce:
1. Create task
2. Create account
3. Go to this account page (accounts/1)
4. Select Task
5. Write task name

Same for all entities
Works on 0.16.x

### PR DESCRIPTION
**Pull request by DmitryAvramec**
Fixes #747

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -47,15 +47,12 @@ def auto_complete
...
       format.json do
-        results = @auto_complete.map do |a|
-          {
-            id: a.id,
-            text: a.respond_to?(:full_name) ? a.full_name : a.name
-          }
+        results = {}
+        @auto_complete.each do |a|
+          text = a.respond_to?(:full_name) ? a.full_name : a.name
+          results.merge!(a.id => text)
```
Comment (johnnyshields) [inline app/controllers/application_controller.rb]: Better to do results[a.id] = ...
