### PR TITLE
Fix tests to be less precise

### LINKED ISSUE #660: Make tests more robust: Task Task/Update should update due date based on selected bucket within different timezone
```
Task Task/Update should update due date based on selected bucket within different timezone
     Failure/Error: expect(task.due_at).to eq(Time.zone.now.end_of_week)
     
       expected: 2018-01-07 23:59:59.999999999 +0000
            got: 2018-01-07 23:59:59.000000000 +0000
     
       (compared using ==)
     
       Diff:
```
Fails for https://travis-ci.org/fatfreecrm/fat_free_crm/jobs/325689495 (mysql).

I don't think anyone reasonably cares about microseconds

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes #660

### CODE REVIEW

File: app/models/polymorphic/task.rb [hunk 1]
```diff
@@ -230,12 +230,12 @@ def set_due_date
 
   #----------------------------------------------------------------------------
   def due_end_of_day?
-    due_at.present? && (due_at == due_at.end_of_day)
+    due_at.present? && (due_at.iso8601 == due_at.end_of_day.iso8601)
```
Comment (johnnyshields) [inline app/models/polymorphic/task.rb]: How about using `.round` method rather than converting to string?

File: app/models/polymorphic/task.rb [hunk 2]
```diff
@@ -230,12 +230,12 @@ def set_due_date
...
   end
 
   #----------------------------------------------------------------------------
   def due_beginning_of_day?
-    due_at.present? && (due_at == due_at.beginning_of_day)
+    due_at.present? && (due_at.iso8601 == due_at.beginning_of_day.iso8601)
```
Comment (johnnyshields) [inline app/models/polymorphic/task.rb]: Don't thing this change is needed; usec will be 0 either way.
